name: cpu-torch-latest
on:
  push:
    branches:
      - main

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}
jobs:
  unit-tests:
    runs-on: ubuntu-24.04
    steps:
      - name: Start Energy Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          task: start-measurement
      - uses: actions/checkout@v4
      - id: setup-venv
        uses: ./.github/workflows/setup-venv
      - name: Install system packages
        run: 'sudo apt-get install -y numactl pdsh

          '
      - id: measurement-4
        name: Record Measurement After Install system packages
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          label: Install system packages
          task: get-measurement
      - name: Install pytorch
        run: 'pip install torch torchvision --index-url https://download.pytorch.org/whl/cpu

          python -c "import torch; print(''torch:'', torch.__version__, torch)"

          python -c "import torch; print(''CUDA available:'', torch.cuda.is_available())"

          '
      - id: measurement-6
        name: Record Measurement After Install pytorch
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          label: Install pytorch
          task: get-measurement
      - name: Install transformers
        run: 'git clone https://github.com/huggingface/transformers

          cd transformers

          # if needed switch to the last known good SHA until transformers@master
          is fixed

          # git checkout 6c3f168b3

          git rev-parse --short HEAD

          pip install .

          '
      - id: measurement-8
        name: Record Measurement After Install transformers
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          label: Install transformers
          task: get-measurement
      - name: Install deepspeed
        run: 'pip install .[dev,autotuning]

          ds_report

          '
      - id: measurement-10
        name: Record Measurement After Install deepspeed
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          label: Install deepspeed
          task: get-measurement
      - name: Python environment
        run: 'pip list

          '
      - id: measurement-12
        name: Record Measurement After Python environment
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          label: Python environment
          task: get-measurement
      - name: Unit tests
        run: 'unset TORCH_CUDA_ARCH_LIST # only jit compile for current arch

          cd tests

          HF_HOME=/tmp/hf_home/ pytest $PYTEST_OPTS -n 4 unit/ --torch_ver="2.6"

          HF_HOME=/tmp/hf_home/ pytest $PYTEST_OPTS -m ''sequential'' unit/ --torch_ver="2.6"

          '
      - id: measurement-14
        name: Record Measurement After Unit tests
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          label: Unit tests
          task: get-measurement
      - id: display-measurement
        name: Display Energy Results
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          task: display-results
      - name: Save Total Energy Consumption Data
        run: echo '${{ steps.final-measurement.outputs.data-total-json }}' > total_energy_consumption.json
      - name: Upload Energy Consumption Artifact
        uses: actions/upload-artifact@v4
        with:
          name: total-energy-consumption
          path: total_energy_consumption.json
