name: nv-ds-chat
on:
  push:
    branches:
      - main

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}
jobs:
  unit-tests:
    runs-on:
      - self-hosted
      - nvidia
      - cu124
      - v100
    steps:
      - name: Start Energy Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          task: start-measurement
      - uses: actions/checkout@v4
      - id: setup-venv
        uses: ./.github/workflows/setup-venv
      - name: Install pytorch
        run: 'pip install -U --cache-dir $TORCH_CACHE torch torchvision --index-url
          https://download.pytorch.org/whl/cu124

          python -c "import torch; print(''torch:'', torch.__version__, torch)"

          python -c "import torch; print(''CUDA available:'', torch.cuda.is_available())"

          '
      - id: measurement-4
        name: Record Measurement After Install pytorch
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          label: Install pytorch
          task: get-measurement
      - name: Install deepspeed
        run: 'pip install transformers

          pip install .[dev]

          ds_report

          '
      - id: measurement-6
        name: Record Measurement After Install deepspeed
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          label: Install deepspeed
          task: get-measurement
      - name: Install deepspeed-chat
        run: "BRANCH=\"master\"\nif [[ ! -z \"${{ github.event.inputs.dse_branch }}\"\
          \ ]]; then\n    BRANCH=\"${{ github.event.inputs.dse_branch }}\"\nfi\necho\
          \ \"DeepSpeedExamples Branch: $BRANCH\"\ngit clone -b $BRANCH https://github.com/deepspeedai/DeepSpeedExamples.git\n\
          cd DeepSpeedExamples/applications/DeepSpeed-Chat\npip install -r requirements.txt\n\
          pip install -e .\n"
      - id: measurement-8
        name: Record Measurement After Install deepspeed-chat
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          label: Install deepspeed-chat
          task: get-measurement
      - name: Python environment
        run: 'pip list

          '
      - id: measurement-10
        name: Record Measurement After Python environment
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          label: Python environment
          task: get-measurement
      - name: DS-Chat unit tests
        run: 'cd DeepSpeedExamples/applications/DeepSpeed-Chat

          unset TORCH_CUDA_ARCH_LIST # only jit compile for current arch

          unset NCCL_DEBUG

          cd tests

          pytest $PYTEST_OPTS ./

          '
      - id: measurement-12
        name: Record Measurement After DS-Chat unit tests
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          label: DS-Chat unit tests
          task: get-measurement
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: ${{ failure() && (github.event_name == 'schedule') }}
        name: Open GitHub issue if nightly CI fails
        uses: JasonEtco/create-an-issue@v2
        with:
          filename: .github/ISSUE_TEMPLATE/ci_failure_report.md
          update_existing: true
      - id: display-measurement
        name: Display Energy Results
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          task: display-results
      - name: Save Total Energy Consumption Data
        run: echo '${{ steps.final-measurement.outputs.data-total-json }}' > total_energy_consumption.json
      - name: Upload Energy Consumption Artifact
        uses: actions/upload-artifact@v4
        with:
          name: total-energy-consumption
          path: total_energy_consumption.json
permissions:
  contents: read
  issues: write
